# Prometheus configuration for Task Management API
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Task API metrics
  - job_name: 'task-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # PostgreSQL metrics (if you add postgres_exporter in the future)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres_exporter:9187']

  # Redis metrics (if you add redis_exporter in the future)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis_exporter:9121']

  # Nginx metrics (if you add nginx_exporter in the future)
  # - job_name: 'nginx'
  #   static_configs:
  #     - targets: ['nginx_exporter:9113']