"""Add priority field to tasks

Revision ID: 25a263a2ffc6
Revises: 36a34e4dc756
Create Date: 2025-08-08 13:31:52.057640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25a263a2ffc6'
down_revision: Union[str, Sequence[str], None] = '36a34e4dc756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priority', sa.Integer(), nullable=True))
    
    # Set default value for existing records
    op.execute("UPDATE tasks SET priority = 0 WHERE priority IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###
